// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBoPr8UPuQKdxP1U-fOVNQAbAg_kNOJHA',
    appId: '1:471930760479:web:147c3fd49f1bd083a0942a',
    messagingSenderId: '471930760479',
    projectId: 'yatra-saathi-2801',
    authDomain: 'yatra-saathi-2801.firebaseapp.com',
    storageBucket: 'yatra-saathi-2801.firebasestorage.app',
    measurementId: 'G-QJD9PXD8G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhCidTtIKLdMRjd8vzPdgBF3ivWB_7Akk',
    appId: '1:471930760479:android:6d1626f5721304d2a0942a',
    messagingSenderId: '471930760479',
    projectId: 'yatra-saathi-2801',
    storageBucket: 'yatra-saathi-2801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGKYd0SpsCH_7Nh2Reuz9y2PTCfKHxOlQ',
    appId: '1:471930760479:ios:e116906fea294f7da0942a',
    messagingSenderId: '471930760479',
    projectId: 'yatra-saathi-2801',
    storageBucket: 'yatra-saathi-2801.firebasestorage.app',
    iosBundleId: 'com.example.yatraSaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGKYd0SpsCH_7Nh2Reuz9y2PTCfKHxOlQ',
    appId: '1:471930760479:ios:e116906fea294f7da0942a',
    messagingSenderId: '471930760479',
    projectId: 'yatra-saathi-2801',
    storageBucket: 'yatra-saathi-2801.firebasestorage.app',
    iosBundleId: 'com.example.yatraSaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBoPr8UPuQKdxP1U-fOVNQAbAg_kNOJHA',
    appId: '1:471930760479:web:f11b12c814794bbea0942a',
    messagingSenderId: '471930760479',
    projectId: 'yatra-saathi-2801',
    authDomain: 'yatra-saathi-2801.firebaseapp.com',
    storageBucket: 'yatra-saathi-2801.firebasestorage.app',
    measurementId: 'G-EJTTF0HT63',
  );
}
